### PR TITLE
IT-1228: Refactor repo to use isxcore C++ API

### PR DESCRIPTION
**Pull request by nosheen-adil**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Refactor the python API so that it's no longer a pure python implementation. Instead this API is a wrapper around the `isxcore` C++ API, used in the IDPS GUI and IDPS Python/MATLAB APIs.

## Related Issues & Documents

- Related Issue #
- Closes #

## Testing Instructions

Added all python unit tests from IDPS repo.

* Follow the setup instructions in the [README](https://github.com/inscopix/pyisx/blob/34191df5a45cae1fc01fc3230f7730ef1105ccb6/README.md)
* Ensure you have the third party and test data folders used to build/test IDPS available on your machine (will be in mosaic2 dir)
* Build the lib and run the unit tests: make test THIRD_PARTY_DIR=/path/to/mosaic2/third_party TEST_DATA_DIR=/path/to/mosaic2/test_data

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by sg-s** [comment]
i am curious to learn how users can install this on macos/arm64 __outside__ of a conda environment

**Comment by nosheen-adil** [comment]
> i am curious to learn how users can install this on macos/arm64 outside of a conda environment

@sg-s Unfortunately the isxcore c++ api is not compatible with arm64 on macos yet. This is another big revamp of the api that I want to prioritize for this year, but it's not in the scope of this PR.

For the time being, users can use the previous, limited, pure python api version. Another option is creating a Docker image with the Linux version of the api installed so that users with Apple Silicon can use this api. Do you think that would be helpful?

**Comment by sg-s** [comment]
i see. a lot of my original motivation was just the ability to read isxd files on macOS/arm64. excited to see the new c++ api when it's compiled for arm64!

**Review by Zachary-Ip — APPROVED** [review]
The wheel file works for me, and I don't see anything concerning to open source!

**Pull request merged**
